"""empty message

Revision ID: d11caed4096a
Revises: 
Create Date: 2021-06-09 18:23:20.504288

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd11caed4096a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Actor')
    op.drop_table('Movie')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Movie',
    sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Movie_id_seq"\'::regclass)'), autoincrement=True, nullable=False),
    sa.Column('title', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('release_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='Movie_pkey'),
    sa.UniqueConstraint('title', name='Movie_title_key'),
    postgresql_ignore_search_path=False
    )
    op.create_table('Actor',
    sa.Column('id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('age', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('movies_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['movies_id'], ['Movie.id'], name='Actor_movies_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', 'gender', name='Actor_pkey')
    )
    # ### end Alembic commands ###
